language: android
sudo: false
jdk:
    - oraclejdk8

android:
    components:
        - build-tools-28.0.3
env:
    global:
        # Keep gradle from crapping all over the log
        - TERM=dumb

install:
    # Install a sdkmanager version that supports the --licenses switch and
    # accept any Android SDK licenses. The output redirection prevents us from
    # hitting the travis log size limit of 4MB which would fail the build.
    - yes | sdkmanager tools > /dev/null
    - yes | sdkmanager --licenses > /dev/null

    - nvm install 10
    - npm install
    - npm install -g codecov

script:
    - gradle --version
    - node --version
    - npm --version
    - bash ./build.sh

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: platforms/android/app/build/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    tags: true